#ifndef TIN_NFS_CODES_H
#define TIN_NFS_CODES_H
#define ERROR -1;
#define OK 1;

///requests type
#define CONNECTION_REQUEST 0
#define CONNECTION_RESPONSE 1

#define OPEN_FILE_REQUEST 2
#define OPEN_FILE_RESPONSE 3

#define READ_FILE_REQUEST 5
#define READ_FILE_RESPONSE 6

#define WRITE_FILE_REQUEST 7
#define WRITE_FILE_RESPONSE 8

#define LSEEK_FILE_REQUEST 9
#define LSEEK_FILE_RESPONSE 10

#define CLOSE_FILE_REQUEST 11
#define CLOSE_FILE_RESPONSE 12

#define UNLINK_FILE_REQUEST 13
#define UNLINK_FILE_RESPONSE 14

#define FSTAT_FILE_REQUEST 15
#define FSTAT_FILE_RESPONSE 16

/// file mode

#define O_RDONLY 0
#define O_WRONLY 1
#define O_RDWR 2
#define O_CREAT 3
#endif //TIN_NFS_CODES_H
